repos:
  # AUTOFLAKE
  - hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
    repo: https://github.com/myint/autoflake
    rev: ''
  # BLACK-   id: autoflake
  - hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=80
    repo: https://github.com/psf/black
    rev: 20.8b1
  # DOCFORMATTER
  - hooks:
      - id: docformatter
        args:
          - -i
          - -r
          - --pre-summary-newline
          - --make-summary-multi-line
    repo: https://github.com/myint/docformatter
    rev: ''
  # ISORT
  - hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=80
    repo: https://github.com/pycqa/isort
    rev: ''
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy